# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

alerting:
  alertmanagers:
  - static_configs:
    - targets:
       - localhost:9093

rule_files:
  - rules_node.yml
  # - "cron_rules.yml"
  # - "second_rules.yml"

scrape_configs:

  - job_name: 'node_exporter'
    file_sd_configs:
      - files:
        - node.yml
        refresh_interval: 5m


